## Numpy

### 向量運算

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])
print(a)
s = 5

[1 2 3]


In [5]:
c = a + s
print(c)
c = a - s
print(c)
c = a * s
print(c)
c = a / s
print(c)

[6 7 8]
[-4 -3 -2]
[ 5 10 15]
[0.2 0.4 0.6]


In [8]:
#乘積和
#向量對應的元素才可計算
a = np.array([1, 2, 3])
s = np.array([3, 4, 5])
c = a.dot(s)
print(c)

26


### 向量長度

In [9]:
store = np.array([2,1])
office = np.array([4,4])

In [10]:
#向量相減仍為向量
#()預設計算到[0,0]的距離
store_office = office - store
norm_store_office = np.linalg.norm(store_office)
norm_store_office

3.605551275463989

### 切割一維陣列

In [12]:
#將list切割
#[start:end]
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
b, c, d = a[2:5], a[:4], a[5:]
print(b, c, d)

[1 2 3 4 5 6 7 8 9]
[3 4 5] [1 2 3 4] [6 7 8 9]


In [13]:
#[start:end:step增量]
b, c, d = a[2:9:3], a[::2], a[::-1]
print(b, c, d)

[3 6 9] [1 3 5 7 9] [9 8 7 6 5 4 3 2 1]


### 矩陣運算

In [16]:
#row*colume
#此為2*3
a = np.array([[1,2,3],[4,5,6]])
print(a)
s = 5

[[1 2 3]
 [4 5 6]]


In [17]:
c = a + s
print(c)
c = a - s
print(c)
c = a * s
print(c)
c = a / s
print(c)

[[ 6  7  8]
 [ 9 10 11]]
[[-4 -3 -2]
 [-1  0  1]]
[[ 5 10 15]
 [20 25 30]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [19]:
a = np.array([[1,2],[3,4]])
s = np.array([[5,6],[7,8]])
print(a)
print(s)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [22]:
#點的位置相乘
w = a * s
print(w)
#點積運算，列行的乘積和
c = a.dot(s)
print(c)

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


### 切割二維陣列

In [27]:
#建立11~35的一維陣列
a = np.arange(11,36)
print(a)
#轉換為5x5的二維陣列
a = a.reshape(5,5)
print(a)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [31]:
b = a[2, 1:3]
print(b)
c = a[1:4, 1]
print(c)
b = a[:2, 1:3]
print(b)
c = a[:, 2]
print(c)
b = a[::2, ::3]
print(b)

[22 23]
[17 22 27]
[[12 13]
 [17 18]]
[13 18 23 28 33]
[[11 14]
 [21 24]
 [31 34]]


### 進階index取出元素

In [33]:
a = np.arange(1,10)
print(a)
b = a[[1,3,5,7]]
print(b)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [34]:
#布林值陣列
b = np.arange(1,7)
#用取餘數的方式，取出偶數
mask = (b % 2 == 0)
print(mask)

[False  True False  True False  True]


In [39]:
a = np.arange(1,37)
a = a.reshape(6,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [40]:
#用tuple取出特定點，表取出位置(0,1)(1,2)(2,3)(3,4)(4,5)的值
c = a[(0,1,2,3,4),(1,2,3,4,5)]
print(c)

[ 2  9 16 23 30]


In [41]:
c = a[3:,[0,2,5]]
print(c)

[[19 21 24]
 [25 27 30]
 [31 33 36]]


In [45]:
#1=True,0=False
mask = np.array([1,0,1,0,0,1],dtype=bool)
c = a[mask,2]
print(c)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### 陣列形狀轉換

In [50]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
c = np.array([[1,2],[3,4],[5,6]])
print(c)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [49]:
#二維轉一維
b = a.ravel()
print(b)
b = np.ravel(a)
print(b)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [52]:
#交換陣列維度
#利用不同維度矩陣相乘
b = c.T
print(b)
b = c.transpose()
print(b)

[[1 3 5]
 [2 4 6]]
[[1 3 5]
 [2 4 6]]


In [55]:
#新增陣列維度
a = np.array([1,2,3])
print(a)
b = a[:,np.newaxis]
print(b)
print(b.shape)

[1 2 3]
[[1]
 [2]
 [3]]
(3, 1)


In [56]:
#陣列複製，不想改變原資料時使用，用'='會改變原資料
b = a.copy()
print(b)

[1 2 3]


In [58]:
#指定陣列元素為單一值
b.fill(3)
print(b)

[3 3 3]


In [60]:
#連接多個一維陣列
c = np.concatenate((a,b))
print(c)

[1 2 3 3 3 3]


In [3]:
#連接多個二維陣列
#axis=0表直向，=1表橫向
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

c = np.concatenate((a,b),axis=0)
print(c)
c = np.concatenate((a,b),axis=1)
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [6]:
#broadcasting，讓不同維度陣列執行數學運算
a = np.array([[11,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
print("a形狀:" + str(a.shape))
b = np.array([1,0,1])
print(b)
print("b形狀:" + str(b.shape))

c = a + b
print(c)

[[11  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a形狀:(4, 3)
[1 0 1]
b形狀:(3,)
[[12  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## Pandas

In [18]:
import pandas as pd

In [3]:
#Series:有索引標籤的一維陣列
s = pd.Series([15,47,32,79])
print(s)

#自訂索引
fruits = ["Apple","Orange","Pear"]
quantities = [34,83,48]
s = pd.Series(quantities, index=fruits)
print(s)
print(s.index)
print(s.values)
print(s["Orange"])
print(s[["Apple","Pear"]])
print((s+10)*2)

0    15
1    47
2    32
3    79
dtype: int64
Apple     34
Orange    83
Pear      48
dtype: int64
Index(['Apple', 'Orange', 'Pear'], dtype='object')
[34 83 48]
83
Apple    34
Pear     48
dtype: int64
Apple      88
Orange    186
Pear      116
dtype: int64


In [11]:
#DataFrame:有索引的二維陣列
fruits = {"Apple":[4,2,5,7],
         "Orange":[1,9,4,7],
         "Pear":[9,3,5,1]}
df = pd.DataFrame(fruits)
df

cities = ["Taipei","Taichung","Tainan","Kaohsiung"]
df = pd.DataFrame(fruits, index=(cites))
df

Apple  Orange  Pear
Taipei         4       1     9
Taichung       2       9     3
Taiwan         5       4     5
Kaohsiung      7       7     1

In [12]:
#columns，重新指定或更改欄位
df = pd.DataFrame(fruits,
                 columns=["Orange","Pear","Apple"],
                  index=cites)
df

Orange  Pear  Apple
Taipei          1     9      4
Taichung        9     3      2
Taiwan          4     5      5
Kaohsiung       7     1      7

In [13]:
df.columns=["Banana","Peach","Apple"]
cities[1]="Taoyuan"
df.index = cities
df

Banana  Peach  Apple
Taipei          1      9      4
Taoyuan         9      3      2
Tainan          4      5      5
Kaohsiung       7      1      7

In [14]:
#轉置
df.T

Taipei  Taoyuan  Tainan  Kaohsiung
Banana       1        9       4          7
Peach        9        3       5          1
Apple        4        2       5          7

### 選擇、過濾、排序

In [20]:
products = {"chanel":["網路","網路","電視","電視","郵購","郵購"],
          "company":["EHS","MOMO","EHS","VIVA","MOMO","EHS"],
          "sales":[11.22,23.50,12.99,15.95,25.75,11.55]}
oridnals = ["A","B","C","D","E","F"]
df = pd.DataFrame(products, index=oridnals)
df

chanel company  sales
A     網路     EHS  11.22
B     網路    MOMO  23.50
C     電視     EHS  12.99
D     電視    VIVA  15.95
E     郵購    MOMO  25.75
F     郵購     EHS  11.55

In [21]:
#選取資料
df[["chanel","company"]].head(2)

chanel company
A     網路     EHS
B     網路    MOMO

In [22]:
#過濾資料
#&即and
df[(df.sales > 15) & (df.sales < 25)]

chanel company  sales
B     網路    MOMO  23.50
D     電視    VIVA  15.95

In [23]:
#排序資料
#True:遞增排序，False:遞減
df.sort_values("sales",ascending=False)

chanel company  sales
E     郵購    MOMO  25.75
B     網路    MOMO  23.50
D     電視    VIVA  15.95
C     電視     EHS  12.99
F     郵購     EHS  11.55
A     網路     EHS  11.22

In [28]:
#更換索引值
#inplace=True:針對原始值做修改，=False:原始值不修改
df.set_index("sales", inplace=False)
#呼叫特定索引值
df.sort_index(axis=0, ascending=False)

chanel company  sales
F     郵購     EHS  11.55
E     郵購    MOMO  25.75
D     電視    VIVA  15.95
C     電視     EHS  12.99
B     網路    MOMO  23.50
A     網路     EHS  11.22

In [30]:
#更新純量值
df.loc["A","sales"] = 9.6
df.iloc[1,2] = 22.01
df.head(2)

#更新單筆紀錄
r = ["郵購","VIVA","18.9"]
df.loc["C"] = r
df.head(3)

chanel company  sales
A     網路     EHS    9.6
B     網路    MOMO  22.01
C     郵購    VIVA   18.9

In [31]:
#更新或刪除資料
s = [10, 20, 30, 40, 50, 60]
#=None，即刪除(僅刪除純量值，位置依然存在)
df.loc[:,"sales"] = s
df.head()

C:\Users\USER1\AppData\Local\Temp\ipykernel_10520\823788207.py:3: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[:,"sales"] = s


chanel company  sales
A     網路     EHS     10
B     網路    MOMO     20
C     郵購    VIVA     30
D     電視    VIVA     40
E     郵購    MOMO     50